# -*- coding: utf-8 -*-
"""Fine_tuning_llama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FRq0LCGr32VT2ceHTYJS7j8faTZwH3Uk
"""
# -*- coding: utf-8 -*-

"""Fine-tuning Llama Model (Llama-2) on Custom Dataset

This script fine-tunes a Llama-2 model for causal language modeling (text generation).
It uses the `datasets`, `transformers`, and `peft` libraries for dataset loading, model training, and parameter-efficient fine-tuning (LoRA).
"""

# Install dependencies
!pip install datasets
!pip install transformers -U
!pip install accelerate -U
!pip install trl
!pip install bitsandbytes
!pip install peft

import torch
import time
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
import bitsandbytes as bnb
from transformers import BitsAndBytesConfig

# Set device (GPU if available)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Dataset and Model Configuration
DATASET_NAME = "ChrisHayduk/Llama-2-SQL-Dataset"
MODEL_NAME = "NousResearch/Llama-2-7b-hf"

# Load the dataset
dataset = load_dataset(DATASET_NAME)
full_training_dataset = dataset["train"]

# Shuffle and select the first 1000 data points for training
training_dataset = full_training_dataset.shuffle().select(range(1000))

# Model and Tokenizer Setup
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype="float16"
)

# Retry logic for loading the tokenizer
max_retries = 3
retry_delay = 5
for retry in range(max_retries):
    try:
        tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True, timeout=60)
        break
    except ReadTimeout:
        if retry < max_retries - 1:
            print(f"Read timeout. Retrying in {retry_delay} seconds... (Attempt {retry + 1}/{max_retries})")
            time.sleep(retry_delay)
        else:
            raise

# Set padding token
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

# Preprocessing the dataset
def construct_datapoint(x):
    combined = x['input'] + x['output']
    return tokenizer(combined, padding=True)

# Apply the preprocessing function to the dataset
training_dataset = training_dataset.map(construct_datapoint)

# LoRA Configuration for Parameter-Efficient Fine-Tuning
peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=['q_proj', 'k_proj', 'down_proj', 'v_proj', 'gate_proj', 'o_proj', 'up_proj'],
    lora_dropout=0.05,
    task_type='CAUSAL_LM'
)

# Load and prepare the model for training
model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, quantization_config=quantization_config)
model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, peft_config)

# Set generation configurations
generation_configuration = model.generation_config
generation_configuration.pad_token_id = tokenizer.eos_token_id
generation_configuration.eos_token_id = tokenizer.eos_token_id
generation_configuration.max_new_tokens = 256
generation_configuration.temperature = 0.7
generation_configuration.top_p = 0.9
generation_configuration.do_sample = True

# Function to generate text based on a prompt
def generate(prompt):
    generation_configuration.max_new_tokens = 20
    encoded = tokenizer.encode(prompt, add_special_tokens=True, return_tensors='pt').to(device)
    with torch.inference_mode():
        out = model.generate(input_ids=encoded, generation_config=generation_configuration, repetition_penalty=2.0)
    decoded_string = tokenizer.decode(out[0], clean_up_tokenization_spaces=True)
    print(decoded_string)

# Test generation with a sample prompt
generate('today I want to')

# Training configuration
training_arguments = transformers.TrainingArguments(
    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,
    num_train_epochs=1,
    learning_rate=2e-4,
    fp16=True,
    optim="paged_adamw_8bit",
    lr_scheduler_type="cosine",
    warmup_ratio=0.05,
    output_dir="fine_tuning",
    report_to='none'
)

# Initialize Trainer
trainer = transformers.Trainer(
    model=model,
    train_dataset=training_dataset,
    args=training_arguments,
    data_collator=transformers.DataCollatorForLanguageModeling(tokenizer, mlm=False)
)

# Disable cache for model configuration
model.config.use_cache = False

# Start training
trainer.train()

# Evaluation
evaluation_dataset = dataset['eval'].shuffle()
sample_sql_question = evaluation_dataset[0]['input']
correct_answer = evaluation_dataset[0]['output']
generate(sample_sql_question)

# Display the correct answer
print("Correct answer:", correct_answer)
